### PR TITLE
Fixes #21 - PHP 7.3.x errors

### LINKED ISSUE #21: StorableObject: PHP 7.3.3 Warning
https://github.com/WildcardSearch/MyBB-Helper-Classes/blob/f2171e52a7a2398cf8ca2b76ee422bb629a1e3b7/src/StorableObject010000.php#L124-L125

Those two lines can be removed to solve the issue and also because they are completely unnecessary.

Thanks to @eldenroot for finding this.

### PR DESCRIPTION
**Pull request by Eldenroot**
Fixes #21

### CODE REVIEW

**Comment by WildcardSearch** [comment]
Thank you so much for helping.

We will need to bump the version by the lowest point, so the new version is 1.0.1 or `StorableObject010001` which means the file needs to be renamed and so does the class.

Also, I don't accept PRs to the `master` branch, so you will need to rebase to this branch I just created: https://github.com/WildcardSearch/MyBB-Helper-Classes/tree/storable-1.0.1

**Comment by WildcardSearch** [comment]
@Eldenroot do you have time to update this PR?

**Comment by Eldenroot** [comment]
I would like to but I cannot push my PR to non existed branch... I see only master.

**Comment by WildcardSearch** [comment]
I linked to the branch above, but it is okay. I will just handle it myself.

**Pull request closed without merging**
